### ISSUE TITLE
What about Route?

### ISSUE THREAD

**Issue by bharrisaplus** [altjs/router#10]
Hello, just wondering why Route wasn't exported from react-router? Upon first using AltRouter I was confused as to where Router was defined, was the idea to just keep this module as DRY and possible since Route isn't modified or was there some other purpose?

**Comment by taion** [comment]
We'd prefer for extensions to React Router to not re-export the React Router modules unless there's a specific need – it makes things more confusing all around, and would just be a bunch of boilerplate all-around (e.g. what about `<IndexRoute>`, `<Link>`, and the rest?).

As React Router is a peer dependency rather than a direct dependency, you'd need to have it explicitly installed anyway, so you should manage the import as well.

**Comment by bharrisaplus** [comment]
Makes sense, thanks for the quick response!
